/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          50:  '#EBF5FF',
          100: '#D6EBFF',
          200: '#ADD6FF',
          300: '#85C2FF',
          400: '#5CADFF',
          500: '#3399FF',
          600: '#0066CC',
          700: '#004D99',
          800: '#003366',
          900: '#001A33',
        },
        surface: {
          DEFAULT: '#F8F9FA',
          card:    '#FFFFFF',
          hover:   '#F1F3F5',
          border:  '#E9ECEF',
          divider: '#DEE2E6',
        },
        content: {
          primary:   '#1A1A2E',
          secondary: '#6C757D',
          tertiary:  '#ADB5BD',
          inverse:   '#FFFFFF',
        },
        success: { light: '#D1FAE5', DEFAULT: '#198754', dark: '#0F5132' },
        warning: { light: '#FFF3CD', DEFAULT: '#FFC107', dark: '#664D03' },
        danger:  { light: '#F8D7DA', DEFAULT: '#DC3545', dark: '#842029' },
        info:    { light: '#CFF4FC', DEFAULT: '#0DCAF0', dark: '#055160' },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        xs:    ['0.75rem',   { lineHeight: '1rem' }],
        sm:    ['0.8125rem', { lineHeight: '1.25rem' }],
        base:  ['0.875rem',  { lineHeight: '1.5rem' }],
        lg:    ['1rem',      { lineHeight: '1.5rem' }],
        xl:    ['1.125rem',  { lineHeight: '1.75rem' }],
        '2xl': ['1.25rem',   { lineHeight: '1.75rem' }],
        '3xl': ['1.5rem',    { lineHeight: '2rem' }],
        '4xl': ['2rem',      { lineHeight: '2.5rem' }],
      },
      spacing: {
        '4.5': '1.125rem',
        '13':  '3.25rem',
        '15':  '3.75rem',
        '18':  '4.5rem',
        '22':  '5.5rem',
      },
      borderRadius: {
        card:   '12px',
        button: '8px',
        badge:  '6px',
        input:  '8px',
      },
      boxShadow: {
        card:        '0 1px 3px 0 rgb(0 0 0 / 0.04), 0 1px 2px -1px rgb(0 0 0 / 0.04)',
        'card-hover':'0 4px 6px -1px rgb(0 0 0 / 0.06), 0 2px 4px -2px rgb(0 0 0 / 0.04)',
        dropdown:    '0 4px 16px -2px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.06)',
        modal:       '0 20px 60px -12px rgb(0 0 0 / 0.15)',
      },
      animation: {
        'fade-in':        'fadeIn 0.3s ease-out',
        'slide-up':       'slideUp 0.3s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'pulse-soft':     'pulseSoft 2s ease-in-out infinite',
        'progress':       'progress 1s ease-out forwards',
        'count-up':       'countUp 0.6s ease-out',
        'scale-in':       'scaleIn 0.2s ease-out',
      },
      keyframes: {
        fadeIn:       { '0%': { opacity: '0' },                                      '100%': { opacity: '1' } },
        slideUp:      { '0%': { opacity: '0', transform: 'translateY(12px)' },       '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideInRight: { '0%': { opacity: '0', transform: 'translateX(12px)' },       '100%': { opacity: '1', transform: 'translateX(0)' } },
        pulseSoft:    { '0%, 100%': { opacity: '1' },                                '50%':  { opacity: '0.7' } },
        progress:     { '0%': { width: '0%' },                                       '100%': { width: 'var(--progress-width)' } },
        countUp:      { '0%': { opacity: '0', transform: 'translateY(8px)' },        '100%': { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:      { '0%': { opacity: '0', transform: 'scale(0.95)' },            '100%': { opacity: '1', transform: 'scale(1)' } },
      },
      transitionTimingFunction: {
        'bounce-sm': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
}
